---
- hosts: all
  vars:
    yum_disablerepo: "*"
    yum_enablerepo: local
    cloud_service_globals_yml: /etc/cloud-service/globals.yml
  #读取外部配置文件这里的配置似乎无效，准备repo，关闭防火墙之类的
  tasks:
    # 读取外部配置文件内容，并注入
    - name: "include {{ cloud_service_globals_yml }} file"
      include_vars:
        file: "{{ cloud_service_globals_yml }}"
      tags:
        - always

    - name: prepare http local repo
      import_role:
        name: httprepo
      tags:
        - repo

    - name: disable firewalld
      import_role:
        name: disable_firewalld
      tags:
        - firewalld
        - os

    - name: disable selinux
      import_role:
        name: disable_selinux
      tags:
        - selinux
        - os
# 安装包
    - name: install required packages
      import_role:
        name: install_packages
      tags:
        - package
        - os

    - name: config docker-ce
      import_role:
        name: docker
      tags:
        - docker

- hosts: all
  # 复制deploy节点的/ect/hosts文件到worker节点
  tasks:
    - name: copy ect hosts
      import_role:
        name: push_etc_hosts
  # 复制证书到worker节点
    - name: copy certificates
      import_role:
        name: copy_certifications
      when:
        - enable_tls | bool
# 从这里开始真正的启动项目所需要的容器之类的
# 安装 haproxy 并启动
- hosts: haproxy
  tags:
    - haproxy
  tasks:
    - name: install haproxy
      import_role:
        name: haproxy
        tasks_from: upgrade.yml
# 安装 rabbitmq 并启动
- hosts: rabbitmq
  tasks:
    - name: install rabbitmq
      import_role:
        name: rabbitmq
        tasks_from: upgrade.yml
      tags:
        - rabbitmq
# 安装 mariadb 并启动
- hosts: mariadb
  tags:
    - mariadb
  tasks:
    - name: install mariadb
      import_role:
        name: mariadb
        tasks_from: upgrade.yml

# 配置定时备份mysql的定时任务
- hosts: mariadb
  tags:
    - cloud_cronjob
  tasks:
    - name: config backup database
      import_role:
        name: cloud_cronjob
        tasks_from: upgrade.yml

# cloud-vpc vpc项目放第一个，能执行python系数据库初始化脚本
- hosts: tomcat
  tasks:
    - name: install tomcat
      import_role:
        name: tomcat
        tasks_from: upgrade.yml
      tags: tomcat

# 在task：cloud-iam之前，生成fernet_setup认证文件，作为配置文件下发到安装节点中，
# 避免出现多节点的一致性问题
- hosts: localhost
  tags:
    - cloud_iam_fernet
  vars:
    cloud_service_globals_yml: /etc/cloud-service/globals.yml
  tasks:
    - name: "include {{ cloud_service_globals_yml }} file"
      include_vars:
        file: "{{ cloud_service_globals_yml }}"

    - name: install cloud cloud iam fernet
      import_role:
        name: cloud_iam_fernet
        tasks_from: upgrade.yml

# Memcached的docker部署
- hosts: cloud_memcached
  tags:
    - cloud_memcached
  vars:
    cloud_service_globals_yml: /etc/cloud-service/globals.yml
  tasks:
    - name: "include {{ cloud_service_globals_yml }} file"
      include_vars:
        file: "{{ cloud_service_globals_yml }}"

    - name: install cloud memcached
      import_role:
        name: memcached
        tasks_from: upgrade.yml

# IAM的docker部署
- hosts: cloud_iam
  tags:
    - cloud_iam
  vars:
    cloud_service_globals_yml: /etc/cloud-service/globals.yml
  tasks:
    - name: "include {{ cloud_service_globals_yml }} file"
      include_vars:
        file: "{{ cloud_service_globals_yml }}"

    - name: install cloud iam
      import_role:
        name: cloud_iam
        tasks_from: upgrade.yml


# RMS的docker部署
- hosts: resource_management
  tags:
    - resource_management
  vars:
    cloud_service_globals_yml: /etc/cloud-service/globals.yml
  tasks:
    - name: "include {{ cloud_service_globals_yml }} file"
      include_vars:
        file: "{{ cloud_service_globals_yml }}"

    - name: install resource management
      import_role:
        name: resource_management
        tasks_from: upgrade.yml


# cloud-service(ECS)的docker部署
- hosts: cloud_service
  tags:
    - cloud_service
  vars:
    cloud_service_globals_yml: /etc/cloud-service/globals.yml
  tasks:
    - name: "include {{ cloud_service_globals_yml }} file"
      include_vars:
        file: "{{ cloud_service_globals_yml }}"

    - name: install cloud service
      import_role:
        name: cloud_service
        tasks_from: upgrade.yml

# cloud-dns的docker部署
- hosts: cloud_dns
  tags:
    - cloud_dns
  vars:
    cloud_service_globals_yml: /etc/cloud-service/globals.yml
  tasks:
    - name: "include {{ cloud_service_globals_yml }} file"
      include_vars:
        file: "{{ cloud_service_globals_yml }}"

    - name: install cloud_dns
      import_role:
        name: cloud_dns
        tasks_from: upgrade.yml

# cloud-trail的docker部署
- hosts: cloud_trail
  tags:
    - cloud_trail
  vars:
    cloud_service_globals_yml: /etc/cloud-service/globals.yml
  tasks:
    - name: "include {{ cloud_service_globals_yml }} file"
      include_vars:
        file: "{{ cloud_service_globals_yml }}"

    - name: install cloud_trail
      import_role:
        name: cloud_trail
        tasks_from: upgrade.yml

# cloud-monitor的docker部署
- hosts: cloud_monitor
  tags:
    - cloud_monitor
  vars:
    cloud_service_globals_yml: /etc/cloud-service/globals.yml
  tasks:
    - name: "include {{ cloud_service_globals_yml }} file"
      include_vars:
        file: "{{ cloud_service_globals_yml }}"

    - name: install cloud_monitor
      import_role:
        name: cloud_monitor
        tasks_from: upgrade.yml

# all portal的docker部署
# ecs 的portal
- hosts: cloud_service_ecs_portal
  tags:
    - cloud_service_ecs_portal
  vars:
    cloud_service_globals_yml: /etc/cloud-service/globals.yml
  tasks:
    - name: "include {{ cloud_service_globals_yml }} file"
      include_vars:
        file: "{{ cloud_service_globals_yml }}"

    - name: install cloud_service_ecs_portal
      import_role:
        name: cloud_service_ecs_portal

# vpc 的portal
- hosts: cloud_service_vpc_portal
  tags:
    - cloud_service_vpc_portal
  vars:
    cloud_service_globals_yml: /etc/cloud-service/globals.yml
  tasks:
    - name: "include {{ cloud_service_globals_yml }} file"
      include_vars:
        file: "{{ cloud_service_globals_yml }}"

    - name: install cloud_service_vpc_portal
      import_role:
        name: cloud_service_vpc_portal

# trail 的portal
- hosts: cloud_service_trail_portal
  tags:
    - cloud_service_trail_portal
  vars:
    cloud_service_globals_yml: /etc/cloud-service/globals.yml
  tasks:
    - name: "include {{ cloud_service_globals_yml }} file"
      include_vars:
        file: "{{ cloud_service_globals_yml }}"

    - name: install cloud_service_trail_portal
      import_role:
        name: cloud_service_trail_portal

# dedicated 的portal
- hosts: cloud_service_dedicated_portal
  tags:
    - cloud_service_dedicated_portal
  vars:
    cloud_service_globals_yml: /etc/cloud-service/globals.yml
  tasks:
    - name: "include {{ cloud_service_globals_yml }} file"
      include_vars:
        file: "{{ cloud_service_globals_yml }}"

    - name: install cloud_service_dedicated_portal
      import_role:
        name: cloud_service_dedicated_portal

# management 的portal
- hosts: cloud_service_management_portal
  tags:
    - cloud_service_management_portal
  vars:
    cloud_service_globals_yml: /etc/cloud-service/globals.yml
  tasks:
    - name: "include {{ cloud_service_globals_yml }} file"
      include_vars:
