---
############
# 删除容器，数据目录 #
############

- name: remove {{ cloud_coreDns_container_name }} container
  docker_container:
    name: "{{ cloud_coreDns_container_name }}"
    state: absent


# 删除目录
- name: remove {{ cloud_coreDns_container_name }} data folder
  file:
    path: "{{ item }}"
