---
############
# 删除容器，数据目录 #
############
# 删除配置文件目录
- name: remove {{ cloud_iam_fernet_image_name }} data folder
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ cloud_iam_fernet_etc_path }}"
    - "{{ cloud_iam_credential_etc_path }}"


