---
############
# 删除容器，数据目录 #
############
# 删除容器
- name: remove {{ cloud_iam_container_name }} container
  docker_container:
    name: "{{ cloud_iam_container_name }}"
    state: absent

# 删除目录
- name: remove {{ cloud_iam_container_name }} data folder
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ cloud_iam_etc_path }}"
    - "{{ cloud_iam_log_path }}"


