---
- name: Running center cloud-nginx container
  docker_container:
    name: "{{ cloud_nginx_container_name }}"
    image: "{{ cloud_nginx_image_fullname }}"
    pull: "{{ cloud_nginx_image_force_pull }}"
    user: root
    network_mode: host
    restart_policy: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ cloud_nginx_etc_path }}/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "{{ cloud_nginx_etc_path }}/nginx.crt:/etc/nginx/nginx.crt:ro"
      - "{{ cloud_nginx_etc_path }}/nginx.key:/etc/nginx/nginx.key:ro"
      - "{{ cloud_nginx_log_path }}:/var/log/nginx:rw"
  when:
    - cloud_config_mode == "center"

- name: Running province cloud-nginx container
  docker_container:
    name: "{{ cloud_nginx_container_name }}"
    image: "{{ cloud_nginx_image_fullname }}"
    pull: "{{ cloud_nginx_image_force_pull }}"
    user: root
    network_mode: host
    restart_policy: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ cloud_nginx_etc_path }}/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "{{ cloud_nginx_log_path }}:/var/log/nginx:rw"
  when:
    - cloud_config_mode == "province"

- name: Running dedicated center cloud-nginx container
  docker_container:
    name: "{{ cloud_nginx_container_name }}"
    image: "{{ cloud_nginx_image_fullname }}"
    pull: "{{ cloud_nginx_image_force_pull }}"
    user: root
    network_mode: host
    restart_policy: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ cloud_nginx_etc_path }}/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "{{ cloud_nginx_etc_path }}/nginx.crt:/etc/nginx/nginx.crt:ro"
      - "{{ cloud_nginx_etc_path }}/nginx.key:/etc/nginx/nginx.key:ro"
      - "{{ cloud_nginx_log_path }}:/var/log/nginx:rw"
  when:
    - cloud_config_mode == "dedicated"


- name: Running direct center cloud-nginx container
  docker_container:
    name: "{{ cloud_nginx_container_name }}"
    image: "{{ cloud_nginx_image_fullname }}"
    pull: "{{ cloud_nginx_image_force_pull }}"
    user: root
    network_mode: host
    restart_policy: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ cloud_nginx_etc_path }}/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "{{ cloud_nginx_etc_path }}/nginx.crt:/etc/nginx/nginx.crt:ro"
      - "{{ cloud_nginx_etc_path }}/nginx.key:/etc/nginx/nginx.key:ro"
      - "{{ cloud_nginx_log_path }}:/var/log/nginx:rw"
  when:
    - cloud_config_mode == "direct"
