---
- name: remove {{ rabbitmq_container_name }} container
  docker_container:
    name: "{{ rabbitmq_container_name }}"
    state: absent

- name: remove {{ rabbitmq_container_name }} etc folder
  file:
    path: "{{ rabbitmq_etc_path }}"
    state: absent

- name: remove rabbitmq volume
  docker_volume:
    name: rabbitmq
    state: absent
