---
- name: remove {{ mariadb_container_name }} container
  docker_container:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ mariadb_container_name }}"
    - "bootstrap_{{ mariadb_container_name }}"

- name: remove {{ mariadb_container_name }} etc folder
  file:
    path: "{{ mariadb_etc_path }}"
    state: absent

- name: remove mariadb volume
  docker_volume:
    name: mariadb
    state: absent
