---
- name: creating haproxy mysql user
  mysql_user:
    login_host: "{{ mariadb_listen_address }}"
    login_port: "{{ mariadb_listen_port }}"
    login_user: "{{ database_user }}"
    login_password: "{{ database_password }}"
    name: haproxy
    password: ""
    host: "%"
    priv: "*.*:USAGE"

- name: wait for mariadb to be available via haproxy
  wait_for:
    host: "{{ internal_vip_address }}"
    port: "{{ mariadb_listen_port }}"
    connect_timeout: 1
    timeout: 60
    search_regex: "MariaDB"
  register: check_mariadb_vip_port
  until: check_mariadb_vip_port is success
  retries: 10
  delay: 6
  run_once: true
