---
- name: "{{ prefix }} | Starting MariaDB container"
  docker_container:
    command: "/mariadb_start.sh"
    env:
      ARGS: "{{ args|default('') }}"
    name: "{{ mariadb_container_name }}"
    image: "{{ mariadb_image_fullname }}"
    pull: "{{ mariadb_image_force_pull }}"
    user: mysql
    network_mode: host
    restart_policy: always
    restart: "{{ restart|default(omit) }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ mariadb_etc_path }}/galera.cnf:/etc/my.cnf.d/galera.cnf:ro"
      - "{{ mariadb_etc_path }}/mariadb:/etc/sudoers.d/mariadb:ro"
      - "{{ mariadb_etc_path }}/mariadb_start.sh:/mariadb_start.sh:ro"
      - "{{ mariadb_etc_path }}/wsrep-notify.sh:/usr/local/bin/wsrep-notify.sh:ro"
      - /var/log/mariadb:/var/log/mariadb:rw
      - mariadb:/var/lib/mysql:rw

- name: "{{ prefix }} | Waiting the mariadb port"
  wait_for:
    host: "{{ mariadb_listen_address }}"
    port: "{{ mariadb_listen_port }}"
    connect_timeout: 1
    timeout: 60
    search_regex: MariaDB
  register: check_mariadb_port
  until: check_mariadb_port is success
  retries: 10
  delay: 6
