---
##########
# Docker #
##########
docker_registry: ''
tomcat_image_namespace: "cloud-service"
tomcat_image_name: "cloud-vpc"
tomcat_image_tag: "{{ cloud_service_vpc_tag }}"

tomcat_image_force_pull: false

tomcat_image_fullname: "\
{{ docker_registry ~ '/' if docker_registry else '' }}\
{{ tomcat_image_namespace ~ '/' if tomcat_image_namespace else '' }}\
{{ tomcat_image_name }}:\
{{ tomcat_image_tag }}"

tomcat_container_name: "cloud-vpc"

############
# tomcat #
############
tomcat_etc_path: "/etc/{{ tomcat_container_name }}"
tomcat_database_version_path: "{{ tomcat_etc_path }}/database_version"

tomcat_ip_version: 4
tomcat_listen_interface: any
tomcat_listen_port: 8080
tomcat_username: admin
tomcat_password: admint0mcat

tomcat_listen_address: "{{ tomcat_listen_interface|address(ip_version=tomcat_ip_version) }}"

# config files
cloud_vpc_config_files:
  cidr:
    name: cidr.json.j2
    path: "{{ tomcat_etc_path }}/cidr.json"

# sql files
cloud_vpc_database_name: "cloud-vpc"

language: cn

sql_files:
  - 00_cloud_vpc_init_ddl.sql

# java_env
# java.net.preferIPv4Stack (default: false)
# If IPv6 is available on the operating system, the underlying native socket will be an IPv6 socket.
# This allows Java applications to connect to, and accept connections from, both IPv4 and IPv6 hosts.

# If an application has a preference to only use IPv4 sockets, then this property can be set to true.
# The implication is that the application will not be able to communicate with IPv6 hosts.

# java.net.preferIPv6Addresses (default: false)
# If IPv6 is available on the operating system, the default preference is to prefer an IPv4-mapped
# address over an IPv6 address. This is for backward compatibility reasons—for example, applications
# that depend on access to an IPv4-only service, or applications that depend on the %d.%d.%d.%d
# representation of an IP address.
#
# This property can be set to try to change the preferences to use IPv6 addresses over IPv4 addresses.
# This allows applications to be tested and deployed in environments where the application is expected to
# connect to IPv6 services.
# NOTE(lixuehai): if only use IPv4 sockets, then set java.net.preferIPv4Stack=true
# References https://docs.oracle.com/javase/8/docs/technotes/guides/net/ipv6_guide/index.html
java_opts: >-
    -Xms4096m
    -Xmx8192m
    -XX:MaxPermSize=256m
    -XX:-UseSplitVerifier
    -noverify

# license
license_file: "p4lic.properties"

# destroy tasks
tomcat_destroy_all: true

# order
order_url: "172.20.151.100"
order_port: "5000"
