---
##########
# Docker #
##########
docker_registry: ''
cloud_service_trail_portal_image_namespace: "cloud-service"
cloud_service_trail_portal_image_name: "cloud-service-trail-portal"
cloud_service_trail_portal_image_tag: "{{ cloud_service_trail_portal_tag }}"

cloud_service_trail_portal_image_force_pull: false

cloud_service_trail_portal_image_fullname: "\
{{ docker_registry ~ '/' if docker_registry else '' }}\
{{ cloud_service_trail_portal_image_namespace ~ '/' if cloud_service_trail_portal_image_namespace else '' }}\
{{ cloud_service_trail_portal_image_name }}:\
{{ cloud_service_trail_portal_image_tag }}"

cloud_service_trail_portal_container_name: "cloud-service-trail-portal"

############
# portal config #
############
cloud_service_trail_portal_etc_path: "/etc/{{ cloud_service_trail_portal_container_name }}"

# internal endpoints
cloud_service_portal_internal_trail: "http://{{ internal_vip_address }}:{{ internal_trail_port }}/"

# portal  endpoints
trail_portal_endpoint: "http://{{ internal_vip_address }}:{{ trail_dashboard_port }}/trail-portal/"
