---
packages:
  infra:
    - bridge-utils
    - patch
    - MySQL-python
  opstool:
    - python2-pip
    - bash-completion
    - bind-utils
    - curl
    - dstat
    - e2fsprogs
    - ethtool
    - findutils
    - fping
    - git
    - htop
    - httpd
    - iftop
    - iotop
    - iperf3
    - iproute
    - jq
    - lsof
    - net-tools
    - nmap-ncat
    - numactl
    - parallel
    - patch
    - pciutils
    - perf
    - procps-ng
    - psmisc
    - python2-crypto
    - strace
    - sysstat
    - tcpdump
    - telnet
    - tmux
    - traceroute
    - unzip
    - vim-enhanced
    - wget
  client:
    - mariadb
  docker:
    - python2-docker
    - python2-netaddr
