---
##########
# Docker #
##########
docker_registry: ''
cloud_iam_image_namespace: "cloud-service"
cloud_iam_image_name: "cloud-iam"
cloud_iam_image_tag: "{{ cloud_service_iam_tag }}"

cloud_iam_image_force_pull: false

cloud_iam_image_fullname: "\
{{ docker_registry ~ '/' if docker_registry else '' }}\
{{ cloud_iam_image_namespace ~ '/' if cloud_iam_image_namespace else '' }}\
{{ cloud_iam_image_name }}:\
{{ cloud_iam_image_tag }}"

cloud_iam_container_name: "cloud-iam"
