---
- name: import docker registry image
  docker_image:
    name: registry
    tag: "2"
    push: false
    load_path: "/opt/release/registry-image.tar"
    source: load

- name: check /var/lib/registry folder
  stat:
    path: /var/lib/registry
  register: check_registry_path

- name: ensure registry config folder
  file:
    path: "{{ item.path }}"
    state: directory
    recurse: true
  when:
    - item.create|bool
  with_items:
    # NOTE(Jeffrey4l): create directory which has lots of file is very slow,
    # just skip it
    - path: /var/lib/registry
      create: "{{ not check_registry_path.stat.exists|bool }}"
    - path: /etc/docker/registry
      create: true

- name: copy config.yml file
  template:
    src: config.yml.j2
    dest: /etc/docker/registry/config.yml
  notify:
    - restart registry container

- name: unarchive kolla registry file
  unarchive:
    src: "/opt/release/docker-registry.tar"
    dest: /var/lib/registry
  tags:
    - unarchive

- name: start registry container
  docker_container:
    name: registry
    image: registry:2
    restart_policy: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/registry:/var/lib/registry
      - /etc/docker/registry:/etc/docker/registry
